---
title: "Welcome to Computer Science 101"
author: "Sean Rodgers"
section: "Intro"
date: 09/21/2016
output:
  revealjs::revealjs_presentation:
    slide_level: 1
    incremental: true
    
---

# What is Computer Science?

# Origins

- A (human) computer was a person whose job was to compute.
- Likely started as early entry level astronomy workers.
- First publication use in the 1850's in an obituary.

# Development beyond Humans

- Jacquard Loom *(1801)*
    - Invented by Joseph Marie Jacquard 
    - Used punchcards for operations control
- Electromechanical Punched Card Tabulator *(1899)*
    - Herman Hollerith
    - First used in the U.S. Census of 1890
- Internal Business Machines Corporation *(1911)*
    - Merger of Hollerith and competitors
    - Eventually became known only as **IBM**.

# Why Study the Past?

- Where did we come from?
    - Mathmeticians and Astornomers - and a few accountants
    - Looms and counting machines
- Why were computers created?
    - To make life easier!
    - Technology - the application of scientific knowledge for practical purposes, especially in industry