---
title: "Welcome to Computer Science 101"
author: "Sean Rodgers"
section: "Intro"
date: 09/21/2016
output:
  revealjs::revealjs_presentation:
    slide_level: 1
    incremental: true
    
---

# What is Computer Science?

# Origins

- A (human) computer was a person whose job was to compute.
- Employed in many different areas of mathematics and accounting.
- Often worked in groups to process data in parallel. 
- First publication use in the 1850's in an obituary.

# Development beyond Humans

- Jacquard Loom *(1801)*
    - Invented by Joseph Marie Jacquard 
    - Used punchcards for operations control
- Electromechanical Punched Card Tabulator *(1889)*
    - Herman Hollerith
    - First used in the U.S. Census of 1890
- Internal Business Machines Corporation *(1911)*
    - Merger of Hollerith and competitors
    - Eventually became known only as **IBM**.

# Why Study the Past?

- Where did we come from?
    - Mathmeticians and Astornomers - and a few accountants
    - Looms and counting machines
- Why were computers created?
    - To make life easier!
    - Technology - the application of scientific knowledge for practical purposes, especially in industry.
- Where are we going?
    - Applications through the decades focus on business
    - 
# Where do we use computers?

- Computers are employed to assist humans in many different arenas.
    - Applications range from Traffic Management to Biomedical Research
        - *Bonus: What popular book written in the 90's was a warning against un-hindered biomedical research and application?* 
        
# Where do Computer Programmers fit in?

- Computer Programmers are the translators between the machine and the man. 
- Being able to understand what a person wants a computer to do and understanding what a computer can do are very important concepts.
- Computer Programmers are the problem solvers at heart.
- Problem Solvers who push boundries of what was thought to be possible. 